# Generated by Django 2.2.2 on 2019-06-11 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter person's name or nickname", max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Is this person a possible IRG lunch host?')),
                ('num_guest_actions', models.IntegerField(default=0, help_text='Times person has attended IRG lunch')),
                ('num_host_actions', models.IntegerField(default=0, help_text='Times person has hosted IRG lunch')),
                ('last_hosted', models.DateField(default=datetime.datetime(1, 1, 1, 0, 0), help_text='Date of last time person hosted IRG lunch')),
            ],
        ),
        migrations.CreateModel(
            name='HostAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this hosting action', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, help_text='Date of the IRG Lunch hosted', null=True)),
                ('host', models.ForeignKey(help_text='Person who brings IRG lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Person')),
            ],
        ),
        migrations.CreateModel(
            name='GuestAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date of the IRG Lunch attended', null=True)),
                ('note', models.CharField(blank=True, help_text='Note to host, ie, vegetarian', max_length=500)),
                ('guest', models.ForeignKey(help_text='Person who attends IRG lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Person')),
            ],
        ),
    ]
