# Generated by Django 2.2.2 on 2019-06-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(help_text='Note to host, ie, vegetarian', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LunchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date of this IRG Lunch', null=True)),
                ('guest', models.ForeignKey(help_text='People who attend IRG lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.AGuest')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter person's name or nickname", max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Is this person a possible IRG lunch host?')),
            ],
        ),
        migrations.CreateModel(
            name='TheHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_event', models.ForeignKey(help_text='Instance of IRG Lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LunchEvent')),
                ('person', models.ForeignKey(help_text='Person who brings IRG lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Person')),
            ],
        ),
        migrations.AddField(
            model_name='lunchevent',
            name='host',
            field=models.ForeignKey(help_text='Person who brings IRG lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.TheHost'),
        ),
        migrations.AddField(
            model_name='aguest',
            name='lunch_event',
            field=models.ForeignKey(help_text='Instance of IRG Lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LunchEvent'),
        ),
        migrations.AddField(
            model_name='aguest',
            name='person',
            field=models.ForeignKey(help_text='Person who attends IRG lunch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Person'),
        ),
    ]
