# Generated by Django 2.2.5 on 2019-09-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190927_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostaction',
            old_name='comments',
            new_name='comment',
        ),
    ]
